# name: Sync
# 'on':
#   push:
#     branches:
#       - master
# jobs:
#   files:
#     name: Files
#     runs-on: ubuntu-latest
#     steps:
#       - uses: adrianjost/files-sync-action@v1.0.1
#         with:
#           GITHUB_TOKEN: '${{ secrets.GH_PAT }}'
#           FILE_PATTERNS: |-
#             ^\.github\/workflows\/synced-.*\.yml$
#             ^LICENSE\.md$
#           TARGET_REPOS: |-
#             Aficionado45/cordova
#             Aficionado45/web-app

name: Sync Files
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Run GitHub File Sync
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          GH_PAT: ${{ secrets.GH_PAT }}